/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ReferralPolicyRouteImport } from './routes/referral-policy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TiersRouteImport } from './routes/tiers'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as CoursesSlugRouteImport } from './routes/courses/$slug'
import { Route as PaymentCallbackRouteImport } from './routes/payment/callback'
import { Route as VerifyNumberRouteImport } from './routes/verify/$number'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedAdminAnnouncementsIndexRouteImport } from './routes/_authenticated/admin/announcements/index'
import { Route as AuthenticatedAdminAuditIndexRouteImport } from './routes/_authenticated/admin/audit/index'
import { Route as AuthenticatedAdminBlogIndexRouteImport } from './routes/_authenticated/admin/blog/index'
import { Route as AuthenticatedAdminBookingsIndexRouteImport } from './routes/_authenticated/admin/bookings/index'
import { Route as AuthenticatedAdminCoursesIndexRouteImport } from './routes/_authenticated/admin/courses/index'
import { Route as AuthenticatedAdminCoursesIdRouteImport } from './routes/_authenticated/admin/courses/$id'
import { Route as AuthenticatedAdminMessagesIndexRouteImport } from './routes/_authenticated/admin/messages/index'
import { Route as AuthenticatedAdminPaymentsIndexRouteImport } from './routes/_authenticated/admin/payments/index'
import { Route as AuthenticatedAdminProductsIndexRouteImport } from './routes/_authenticated/admin/products/index'
import { Route as AuthenticatedAdminReferralsIndexRouteImport } from './routes/_authenticated/admin/referrals/index'
import { Route as AuthenticatedAdminReportsIndexRouteImport } from './routes/_authenticated/admin/reports/index'
import { Route as AuthenticatedAdminSettingsIndexRouteImport } from './routes/_authenticated/admin/settings/index'
import { Route as AuthenticatedAdminTiersIndexRouteImport } from './routes/_authenticated/admin/tiers/index'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users/index'
import { Route as AuthenticatedAdminUsersIdRouteImport } from './routes/_authenticated/admin/users/$id'
import { Route as AuthenticatedAdminWithdrawalsIndexRouteImport } from './routes/_authenticated/admin/withdrawals/index'
import { Route as AuthenticatedDashboardBlogIndexRouteImport } from './routes/_authenticated/dashboard/blog/index'
import { Route as AuthenticatedDashboardNotificationsIndexRouteImport } from './routes/_authenticated/dashboard/notifications/index'
import { Route as AuthenticatedDashboardProfileIndexRouteImport } from './routes/_authenticated/dashboard/profile/index'
import { Route as AuthenticatedDashboardReferralsIndexRouteImport } from './routes/_authenticated/dashboard/referrals/index'
import { Route as AuthenticatedDashboardTiersIndexRouteImport } from './routes/_authenticated/dashboard/tiers/index'
import { Route as AuthenticatedDashboardTiersSlugRouteImport } from './routes/_authenticated/dashboard/tiers/$slug'
import { Route as AuthenticatedDashboardWalletIndexRouteImport } from './routes/_authenticated/dashboard/wallet/index'
import { Route as AuthenticatedLearnCourseSlugLessonSlugRouteImport } from './routes/_authenticated/learn/$courseSlug/$lessonSlug'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralPolicyRoute = ReferralPolicyRouteImport.update({
  id: '/referral-policy',
  path: '/referral-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TiersRoute = TiersRouteImport.update({
  id: '/tiers',
  path: '/tiers',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCallbackRoute = PaymentCallbackRouteImport.update({
  id: '/payment/callback',
  path: '/payment/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyNumberRoute = VerifyNumberRouteImport.update({
  id: '/verify/$number',
  path: '/verify/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAnnouncementsIndexRoute =
  AuthenticatedAdminAnnouncementsIndexRouteImport.update({
    id: '/announcements/',
    path: '/announcements/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAuditIndexRoute =
  AuthenticatedAdminAuditIndexRouteImport.update({
    id: '/audit/',
    path: '/audit/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBlogIndexRoute =
  AuthenticatedAdminBlogIndexRouteImport.update({
    id: '/blog/',
    path: '/blog/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBookingsIndexRoute =
  AuthenticatedAdminBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCoursesIndexRoute =
  AuthenticatedAdminCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCoursesIdRoute =
  AuthenticatedAdminCoursesIdRouteImport.update({
    id: '/courses/$id',
    path: '/courses/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMessagesIndexRoute =
  AuthenticatedAdminMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsIndexRoute =
  AuthenticatedAdminPaymentsIndexRouteImport.update({
    id: '/payments/',
    path: '/payments/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProductsIndexRoute =
  AuthenticatedAdminProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReferralsIndexRoute =
  AuthenticatedAdminReferralsIndexRouteImport.update({
    id: '/referrals/',
    path: '/referrals/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReportsIndexRoute =
  AuthenticatedAdminReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsIndexRoute =
  AuthenticatedAdminSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTiersIndexRoute =
  AuthenticatedAdminTiersIndexRouteImport.update({
    id: '/tiers/',
    path: '/tiers/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersIdRoute =
  AuthenticatedAdminUsersIdRouteImport.update({
    id: '/users/$id',
    path: '/users/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminWithdrawalsIndexRoute =
  AuthenticatedAdminWithdrawalsIndexRouteImport.update({
    id: '/withdrawals/',
    path: '/withdrawals/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedDashboardBlogIndexRoute =
  AuthenticatedDashboardBlogIndexRouteImport.update({
    id: '/dashboard/blog/',
    path: '/dashboard/blog/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardNotificationsIndexRoute =
  AuthenticatedDashboardNotificationsIndexRouteImport.update({
    id: '/dashboard/notifications/',
    path: '/dashboard/notifications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardProfileIndexRoute =
  AuthenticatedDashboardProfileIndexRouteImport.update({
    id: '/dashboard/profile/',
    path: '/dashboard/profile/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardReferralsIndexRoute =
  AuthenticatedDashboardReferralsIndexRouteImport.update({
    id: '/dashboard/referrals/',
    path: '/dashboard/referrals/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardTiersIndexRoute =
  AuthenticatedDashboardTiersIndexRouteImport.update({
    id: '/dashboard/tiers/',
    path: '/dashboard/tiers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardTiersSlugRoute =
  AuthenticatedDashboardTiersSlugRouteImport.update({
    id: '/dashboard/tiers/$slug',
    path: '/dashboard/tiers/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardWalletIndexRoute =
  AuthenticatedDashboardWalletIndexRouteImport.update({
    id: '/dashboard/wallet/',
    path: '/dashboard/wallet/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearnCourseSlugLessonSlugRoute =
  AuthenticatedLearnCourseSlugLessonSlugRouteImport.update({
    id: '/learn/$courseSlug/$lessonSlug',
    path: '/learn/$courseSlug/$lessonSlug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack/webhook',
    path: '/api/public/paystack/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/forbidden': typeof ForbiddenRoute
  '/maintenance': typeof MaintenanceRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/referral-policy': typeof ReferralPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tiers': typeof TiersRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/verify/$number': typeof VerifyNumberRoute
  '/blog/': typeof BlogIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/admin/courses/$id': typeof AuthenticatedAdminCoursesIdRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/dashboard/tiers/$slug': typeof AuthenticatedDashboardTiersSlugRoute
  '/learn/$courseSlug/$lessonSlug': typeof AuthenticatedLearnCourseSlugLessonSlugRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
  '/admin/announcements/': typeof AuthenticatedAdminAnnouncementsIndexRoute
  '/admin/audit/': typeof AuthenticatedAdminAuditIndexRoute
  '/admin/blog/': typeof AuthenticatedAdminBlogIndexRoute
  '/admin/bookings/': typeof AuthenticatedAdminBookingsIndexRoute
  '/admin/courses/': typeof AuthenticatedAdminCoursesIndexRoute
  '/admin/messages/': typeof AuthenticatedAdminMessagesIndexRoute
  '/admin/payments/': typeof AuthenticatedAdminPaymentsIndexRoute
  '/admin/products/': typeof AuthenticatedAdminProductsIndexRoute
  '/admin/referrals/': typeof AuthenticatedAdminReferralsIndexRoute
  '/admin/reports/': typeof AuthenticatedAdminReportsIndexRoute
  '/admin/settings/': typeof AuthenticatedAdminSettingsIndexRoute
  '/admin/tiers/': typeof AuthenticatedAdminTiersIndexRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/admin/withdrawals/': typeof AuthenticatedAdminWithdrawalsIndexRoute
  '/dashboard/blog/': typeof AuthenticatedDashboardBlogIndexRoute
  '/dashboard/notifications/': typeof AuthenticatedDashboardNotificationsIndexRoute
  '/dashboard/profile/': typeof AuthenticatedDashboardProfileIndexRoute
  '/dashboard/referrals/': typeof AuthenticatedDashboardReferralsIndexRoute
  '/dashboard/tiers/': typeof AuthenticatedDashboardTiersIndexRoute
  '/dashboard/wallet/': typeof AuthenticatedDashboardWalletIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/forbidden': typeof ForbiddenRoute
  '/maintenance': typeof MaintenanceRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/referral-policy': typeof ReferralPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tiers': typeof TiersRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/verify/$number': typeof VerifyNumberRoute
  '/blog': typeof BlogIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/admin/courses/$id': typeof AuthenticatedAdminCoursesIdRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/dashboard/tiers/$slug': typeof AuthenticatedDashboardTiersSlugRoute
  '/learn/$courseSlug/$lessonSlug': typeof AuthenticatedLearnCourseSlugLessonSlugRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsIndexRoute
  '/admin/audit': typeof AuthenticatedAdminAuditIndexRoute
  '/admin/blog': typeof AuthenticatedAdminBlogIndexRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsIndexRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesIndexRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesIndexRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsIndexRoute
  '/admin/products': typeof AuthenticatedAdminProductsIndexRoute
  '/admin/referrals': typeof AuthenticatedAdminReferralsIndexRoute
  '/admin/reports': typeof AuthenticatedAdminReportsIndexRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsIndexRoute
  '/admin/tiers': typeof AuthenticatedAdminTiersIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsIndexRoute
  '/dashboard/blog': typeof AuthenticatedDashboardBlogIndexRoute
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsIndexRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileIndexRoute
  '/dashboard/referrals': typeof AuthenticatedDashboardReferralsIndexRoute
  '/dashboard/tiers': typeof AuthenticatedDashboardTiersIndexRoute
  '/dashboard/wallet': typeof AuthenticatedDashboardWalletIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/forbidden': typeof ForbiddenRoute
  '/maintenance': typeof MaintenanceRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/referral-policy': typeof ReferralPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tiers': typeof TiersRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/verify/$number': typeof VerifyNumberRoute
  '/blog/': typeof BlogIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/admin/courses/$id': typeof AuthenticatedAdminCoursesIdRoute
  '/_authenticated/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/_authenticated/dashboard/tiers/$slug': typeof AuthenticatedDashboardTiersSlugRoute
  '/_authenticated/learn/$courseSlug/$lessonSlug': typeof AuthenticatedLearnCourseSlugLessonSlugRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
  '/_authenticated/admin/announcements/': typeof AuthenticatedAdminAnnouncementsIndexRoute
  '/_authenticated/admin/audit/': typeof AuthenticatedAdminAuditIndexRoute
  '/_authenticated/admin/blog/': typeof AuthenticatedAdminBlogIndexRoute
  '/_authenticated/admin/bookings/': typeof AuthenticatedAdminBookingsIndexRoute
  '/_authenticated/admin/courses/': typeof AuthenticatedAdminCoursesIndexRoute
  '/_authenticated/admin/messages/': typeof AuthenticatedAdminMessagesIndexRoute
  '/_authenticated/admin/payments/': typeof AuthenticatedAdminPaymentsIndexRoute
  '/_authenticated/admin/products/': typeof AuthenticatedAdminProductsIndexRoute
  '/_authenticated/admin/referrals/': typeof AuthenticatedAdminReferralsIndexRoute
  '/_authenticated/admin/reports/': typeof AuthenticatedAdminReportsIndexRoute
  '/_authenticated/admin/settings/': typeof AuthenticatedAdminSettingsIndexRoute
  '/_authenticated/admin/tiers/': typeof AuthenticatedAdminTiersIndexRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/admin/withdrawals/': typeof AuthenticatedAdminWithdrawalsIndexRoute
  '/_authenticated/dashboard/blog/': typeof AuthenticatedDashboardBlogIndexRoute
  '/_authenticated/dashboard/notifications/': typeof AuthenticatedDashboardNotificationsIndexRoute
  '/_authenticated/dashboard/profile/': typeof AuthenticatedDashboardProfileIndexRoute
  '/_authenticated/dashboard/referrals/': typeof AuthenticatedDashboardReferralsIndexRoute
  '/_authenticated/dashboard/tiers/': typeof AuthenticatedDashboardTiersIndexRoute
  '/_authenticated/dashboard/wallet/': typeof AuthenticatedDashboardWalletIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/forbidden'
    | '/maintenance'
    | '/privacy'
    | '/products'
    | '/referral-policy'
    | '/reset-password'
    | '/search'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/tiers'
    | '/unauthorized'
    | '/admin'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/payment/callback'
    | '/verify/$number'
    | '/blog/'
    | '/courses/'
    | '/admin/'
    | '/dashboard/'
    | '/admin/courses/$id'
    | '/admin/users/$id'
    | '/dashboard/tiers/$slug'
    | '/learn/$courseSlug/$lessonSlug'
    | '/api/public/paystack/webhook'
    | '/admin/announcements/'
    | '/admin/audit/'
    | '/admin/blog/'
    | '/admin/bookings/'
    | '/admin/courses/'
    | '/admin/messages/'
    | '/admin/payments/'
    | '/admin/products/'
    | '/admin/referrals/'
    | '/admin/reports/'
    | '/admin/settings/'
    | '/admin/tiers/'
    | '/admin/users/'
    | '/admin/withdrawals/'
    | '/dashboard/blog/'
    | '/dashboard/notifications/'
    | '/dashboard/profile/'
    | '/dashboard/referrals/'
    | '/dashboard/tiers/'
    | '/dashboard/wallet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/forbidden'
    | '/maintenance'
    | '/privacy'
    | '/products'
    | '/referral-policy'
    | '/reset-password'
    | '/search'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/tiers'
    | '/unauthorized'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/payment/callback'
    | '/verify/$number'
    | '/blog'
    | '/courses'
    | '/admin'
    | '/dashboard'
    | '/admin/courses/$id'
    | '/admin/users/$id'
    | '/dashboard/tiers/$slug'
    | '/learn/$courseSlug/$lessonSlug'
    | '/api/public/paystack/webhook'
    | '/admin/announcements'
    | '/admin/audit'
    | '/admin/blog'
    | '/admin/bookings'
    | '/admin/courses'
    | '/admin/messages'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/referrals'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/tiers'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/dashboard/blog'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/referrals'
    | '/dashboard/tiers'
    | '/dashboard/wallet'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/forbidden'
    | '/maintenance'
    | '/privacy'
    | '/products'
    | '/referral-policy'
    | '/reset-password'
    | '/search'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/tiers'
    | '/unauthorized'
    | '/_authenticated/admin'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/payment/callback'
    | '/verify/$number'
    | '/blog/'
    | '/courses/'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/admin/courses/$id'
    | '/_authenticated/admin/users/$id'
    | '/_authenticated/dashboard/tiers/$slug'
    | '/_authenticated/learn/$courseSlug/$lessonSlug'
    | '/api/public/paystack/webhook'
    | '/_authenticated/admin/announcements/'
    | '/_authenticated/admin/audit/'
    | '/_authenticated/admin/blog/'
    | '/_authenticated/admin/bookings/'
    | '/_authenticated/admin/courses/'
    | '/_authenticated/admin/messages/'
    | '/_authenticated/admin/payments/'
    | '/_authenticated/admin/products/'
    | '/_authenticated/admin/referrals/'
    | '/_authenticated/admin/reports/'
    | '/_authenticated/admin/settings/'
    | '/_authenticated/admin/tiers/'
    | '/_authenticated/admin/users/'
    | '/_authenticated/admin/withdrawals/'
    | '/_authenticated/dashboard/blog/'
    | '/_authenticated/dashboard/notifications/'
    | '/_authenticated/dashboard/profile/'
    | '/_authenticated/dashboard/referrals/'
    | '/_authenticated/dashboard/tiers/'
    | '/_authenticated/dashboard/wallet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  ForbiddenRoute: typeof ForbiddenRoute
  MaintenanceRoute: typeof MaintenanceRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRoute
  ReferralPolicyRoute: typeof ReferralPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TiersRoute: typeof TiersRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  PaymentCallbackRoute: typeof PaymentCallbackRoute
  VerifyNumberRoute: typeof VerifyNumberRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral-policy': {
      id: '/referral-policy'
      path: '/referral-policy'
      fullPath: '/referral-policy'
      preLoaderRoute: typeof ReferralPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiers': {
      id: '/tiers'
      path: '/tiers'
      fullPath: '/tiers'
      preLoaderRoute: typeof TiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/callback': {
      id: '/payment/callback'
      path: '/payment/callback'
      fullPath: '/payment/callback'
      preLoaderRoute: typeof PaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$number': {
      id: '/verify/$number'
      path: '/verify/$number'
      fullPath: '/verify/$number'
      preLoaderRoute: typeof VerifyNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/announcements/': {
      id: '/_authenticated/admin/announcements/'
      path: '/announcements'
      fullPath: '/admin/announcements/'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit/': {
      id: '/_authenticated/admin/audit/'
      path: '/audit'
      fullPath: '/admin/audit/'
      preLoaderRoute: typeof AuthenticatedAdminAuditIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/blog/': {
      id: '/_authenticated/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AuthenticatedAdminBlogIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/bookings/': {
      id: '/_authenticated/admin/bookings/'
      path: '/bookings'
      fullPath: '/admin/bookings/'
      preLoaderRoute: typeof AuthenticatedAdminBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/courses/': {
      id: '/_authenticated/admin/courses/'
      path: '/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AuthenticatedAdminCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/courses/$id': {
      id: '/_authenticated/admin/courses/$id'
      path: '/courses/$id'
      fullPath: '/admin/courses/$id'
      preLoaderRoute: typeof AuthenticatedAdminCoursesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/messages/': {
      id: '/_authenticated/admin/messages/'
      path: '/messages'
      fullPath: '/admin/messages/'
      preLoaderRoute: typeof AuthenticatedAdminMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payments/': {
      id: '/_authenticated/admin/payments/'
      path: '/payments'
      fullPath: '/admin/payments/'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/products/': {
      id: '/_authenticated/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AuthenticatedAdminProductsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/referrals/': {
      id: '/_authenticated/admin/referrals/'
      path: '/referrals'
      fullPath: '/admin/referrals/'
      preLoaderRoute: typeof AuthenticatedAdminReferralsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reports/': {
      id: '/_authenticated/admin/reports/'
      path: '/reports'
      fullPath: '/admin/reports/'
      preLoaderRoute: typeof AuthenticatedAdminReportsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings/': {
      id: '/_authenticated/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AuthenticatedAdminSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tiers/': {
      id: '/_authenticated/admin/tiers/'
      path: '/tiers'
      fullPath: '/admin/tiers/'
      preLoaderRoute: typeof AuthenticatedAdminTiersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users/$id': {
      id: '/_authenticated/admin/users/$id'
      path: '/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AuthenticatedAdminUsersIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/withdrawals/': {
      id: '/_authenticated/admin/withdrawals/'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals/'
      preLoaderRoute: typeof AuthenticatedAdminWithdrawalsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/dashboard/blog/': {
      id: '/_authenticated/dashboard/blog/'
      path: '/dashboard/blog'
      fullPath: '/dashboard/blog/'
      preLoaderRoute: typeof AuthenticatedDashboardBlogIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/notifications/': {
      id: '/_authenticated/dashboard/notifications/'
      path: '/dashboard/notifications'
      fullPath: '/dashboard/notifications/'
      preLoaderRoute: typeof AuthenticatedDashboardNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/profile/': {
      id: '/_authenticated/dashboard/profile/'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile/'
      preLoaderRoute: typeof AuthenticatedDashboardProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/referrals/': {
      id: '/_authenticated/dashboard/referrals/'
      path: '/dashboard/referrals'
      fullPath: '/dashboard/referrals/'
      preLoaderRoute: typeof AuthenticatedDashboardReferralsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/tiers/': {
      id: '/_authenticated/dashboard/tiers/'
      path: '/dashboard/tiers'
      fullPath: '/dashboard/tiers/'
      preLoaderRoute: typeof AuthenticatedDashboardTiersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/tiers/$slug': {
      id: '/_authenticated/dashboard/tiers/$slug'
      path: '/dashboard/tiers/$slug'
      fullPath: '/dashboard/tiers/$slug'
      preLoaderRoute: typeof AuthenticatedDashboardTiersSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/wallet/': {
      id: '/_authenticated/dashboard/wallet/'
      path: '/dashboard/wallet'
      fullPath: '/dashboard/wallet/'
      preLoaderRoute: typeof AuthenticatedDashboardWalletIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/$courseSlug/$lessonSlug': {
      id: '/_authenticated/learn/$courseSlug/$lessonSlug'
      path: '/learn/$courseSlug/$lessonSlug'
      fullPath: '/learn/$courseSlug/$lessonSlug'
      preLoaderRoute: typeof AuthenticatedLearnCourseSlugLessonSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/paystack/webhook': {
      id: '/api/public/paystack/webhook'
      path: '/api/public/paystack/webhook'
      fullPath: '/api/public/paystack/webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCoursesIdRoute: typeof AuthenticatedAdminCoursesIdRoute
  AuthenticatedAdminUsersIdRoute: typeof AuthenticatedAdminUsersIdRoute
  AuthenticatedAdminAnnouncementsIndexRoute: typeof AuthenticatedAdminAnnouncementsIndexRoute
  AuthenticatedAdminAuditIndexRoute: typeof AuthenticatedAdminAuditIndexRoute
  AuthenticatedAdminBlogIndexRoute: typeof AuthenticatedAdminBlogIndexRoute
  AuthenticatedAdminBookingsIndexRoute: typeof AuthenticatedAdminBookingsIndexRoute
  AuthenticatedAdminCoursesIndexRoute: typeof AuthenticatedAdminCoursesIndexRoute
  AuthenticatedAdminMessagesIndexRoute: typeof AuthenticatedAdminMessagesIndexRoute
  AuthenticatedAdminPaymentsIndexRoute: typeof AuthenticatedAdminPaymentsIndexRoute
  AuthenticatedAdminProductsIndexRoute: typeof AuthenticatedAdminProductsIndexRoute
  AuthenticatedAdminReferralsIndexRoute: typeof AuthenticatedAdminReferralsIndexRoute
  AuthenticatedAdminReportsIndexRoute: typeof AuthenticatedAdminReportsIndexRoute
  AuthenticatedAdminSettingsIndexRoute: typeof AuthenticatedAdminSettingsIndexRoute
  AuthenticatedAdminTiersIndexRoute: typeof AuthenticatedAdminTiersIndexRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
  AuthenticatedAdminWithdrawalsIndexRoute: typeof AuthenticatedAdminWithdrawalsIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminCoursesIdRoute: AuthenticatedAdminCoursesIdRoute,
    AuthenticatedAdminUsersIdRoute: AuthenticatedAdminUsersIdRoute,
    AuthenticatedAdminAnnouncementsIndexRoute:
      AuthenticatedAdminAnnouncementsIndexRoute,
    AuthenticatedAdminAuditIndexRoute: AuthenticatedAdminAuditIndexRoute,
    AuthenticatedAdminBlogIndexRoute: AuthenticatedAdminBlogIndexRoute,
    AuthenticatedAdminBookingsIndexRoute: AuthenticatedAdminBookingsIndexRoute,
    AuthenticatedAdminCoursesIndexRoute: AuthenticatedAdminCoursesIndexRoute,
    AuthenticatedAdminMessagesIndexRoute: AuthenticatedAdminMessagesIndexRoute,
    AuthenticatedAdminPaymentsIndexRoute: AuthenticatedAdminPaymentsIndexRoute,
    AuthenticatedAdminProductsIndexRoute: AuthenticatedAdminProductsIndexRoute,
    AuthenticatedAdminReferralsIndexRoute:
      AuthenticatedAdminReferralsIndexRoute,
    AuthenticatedAdminReportsIndexRoute: AuthenticatedAdminReportsIndexRoute,
    AuthenticatedAdminSettingsIndexRoute: AuthenticatedAdminSettingsIndexRoute,
    AuthenticatedAdminTiersIndexRoute: AuthenticatedAdminTiersIndexRoute,
    AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
    AuthenticatedAdminWithdrawalsIndexRoute:
      AuthenticatedAdminWithdrawalsIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardTiersSlugRoute: typeof AuthenticatedDashboardTiersSlugRoute
  AuthenticatedLearnCourseSlugLessonSlugRoute: typeof AuthenticatedLearnCourseSlugLessonSlugRoute
  AuthenticatedDashboardBlogIndexRoute: typeof AuthenticatedDashboardBlogIndexRoute
  AuthenticatedDashboardNotificationsIndexRoute: typeof AuthenticatedDashboardNotificationsIndexRoute
  AuthenticatedDashboardProfileIndexRoute: typeof AuthenticatedDashboardProfileIndexRoute
  AuthenticatedDashboardReferralsIndexRoute: typeof AuthenticatedDashboardReferralsIndexRoute
  AuthenticatedDashboardTiersIndexRoute: typeof AuthenticatedDashboardTiersIndexRoute
  AuthenticatedDashboardWalletIndexRoute: typeof AuthenticatedDashboardWalletIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedDashboardTiersSlugRoute: AuthenticatedDashboardTiersSlugRoute,
  AuthenticatedLearnCourseSlugLessonSlugRoute:
    AuthenticatedLearnCourseSlugLessonSlugRoute,
  AuthenticatedDashboardBlogIndexRoute: AuthenticatedDashboardBlogIndexRoute,
  AuthenticatedDashboardNotificationsIndexRoute:
    AuthenticatedDashboardNotificationsIndexRoute,
  AuthenticatedDashboardProfileIndexRoute:
    AuthenticatedDashboardProfileIndexRoute,
  AuthenticatedDashboardReferralsIndexRoute:
    AuthenticatedDashboardReferralsIndexRoute,
  AuthenticatedDashboardTiersIndexRoute: AuthenticatedDashboardTiersIndexRoute,
  AuthenticatedDashboardWalletIndexRoute:
    AuthenticatedDashboardWalletIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  ForbiddenRoute: ForbiddenRoute,
  MaintenanceRoute: MaintenanceRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRoute,
  ReferralPolicyRoute: ReferralPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TiersRoute: TiersRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  BlogSlugRoute: BlogSlugRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  PaymentCallbackRoute: PaymentCallbackRoute,
  VerifyNumberRoute: VerifyNumberRoute,
  BlogIndexRoute: BlogIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
